name: Build and test

on: [push]

jobs:
  ubuntu-18_04:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        compiler: [g++, clang]

    steps:
      - name: Install dependencies
        run: sudo apt install build-essential libasound2-dev libqt5sql5-sqlite libqt5svg5-dev pkg-config qt5-default ${{matrix.compiler}}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure
        run: qmake -spec linux-${{matrix.compiler}}

      - name: Build
        run: make

      - name: Test
        run: make check

  ubuntu-20_04:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        compiler: [g++, clang]

    steps:
      - name: Install dependencies
        run: sudo apt install build-essential libasound2-dev libqt5sql5-sqlite libqt5svg5-dev pkg-config qt5-default ${{matrix.compiler}}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure
        run: qmake -spec linux-${{matrix.compiler}}

      - name: Build
        run: make

      - name: Test
        run: make check
